version: '3.1'
services:
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "${MOUSELIGHT_LOG_VOLUME}:/var/log/nginx"
    extra_hosts:
      - "ml-ubuntu-test:10.123.1.184"
      - "ml-ubuntu-test.hhmi.org:10.123.1.184"
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports:
      - 9400:5601
  landing:
    hostname: landing
    image: mouselightresearch/landing:1.4
    environment:
      NODE_ENV: production
    volumes:
      - "${MOUSELIGHT_LOG_VOLUME}:/var/log/mouselight"
    ports:
      - 8080:5000

volumes:
  esdata:

networks:
  back_tier:
