version: '3.1'
services:
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "${MOUSELIGHT_LOG_VOLUME}:/var/log/nginx"
    extra_hosts:
      - "mouselight.int.janelia.org:${MOUSELIGHT_IP}"
    networks:
      - back_tier
    command: /bin/bash -c "touch /var/log/nginx/nginx-error.log && touch /var/log/nginx/nginx-access.log && chown mluser:mousebrainmicro /var/log/nginx/nginx-*.log && exec nginx -g 'daemon off;'"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - back_tier
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports:
      - 9400:5601
    networks:
      - back_tier
  landing:
    hostname: landing
    image: mouselightresearch/landing:1.4
    environment:
      NODE_ENV: production
    volumes:
      - "${MOUSELIGHT_LOG_VOLUME}:/var/log/mouselight"
    ports:
      - 8080:5000
    networks:
      - back_tier

volumes:
  esdata:

networks:
  back_tier:
